import type { NextPage } from 'next'
import Head from 'next/head'
import style from '../styles/Home.module.scss'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main>
        <h1 className={style.heading}>Welcome to Next.js!</h1>
      </main>
    </div>
  )
}

export default Home
